site_name: Dialogue System
site_description: Documentation for the Dialogue System by CommanderFoo in Community Content
docs_dir: docs
extra_css:
  - styles/extra.css
theme:
  font:
    text: Roboto
    code: Monospace
  palette:
    scheme: slate
    primary: blue
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - navigation.expand
  
nav:
  - Documentation:
    - index.md
    - quick-start.md
    - how.md
    - themes.md
    - replacements.md
    - conditions.md
    - callbacks.md
    - Properties:
      - properties/dialogue-system.md
      - properties/dialogue-conversation.md
      - properties/dialogue-conversation-entry.md
      - properties/dialogue-player-choice.md
    - Tutorial:
      - tutorial/setup.md
      - tutorial/create-npc.md
      - tutorial/database-folder.md
      - tutorial/npc-conversation.md
      - tutorial/npc-trigger.md
      - tutorial/conversation-entry.md
      - tutorial/conversation-choices.md
      - tutorial/replacements.md
      - tutorial/call-events.md
      - tutorial/conditions.md
      - tutorial/condition-functions.md
    - credits.md

  - Core Games:
    - https://coregames.com

  - Twitter:
    - https://twitter.com/PIXELDEPTH

  - GitHub:
    - https://pixeldepth.net

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false